"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-f7qr*k-r973o5$&9=yjro@4z#62nrcnyj4kqy_i5*lf-d%c8*q'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['8.153.95.63', '172.31.180.1', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'apps.marathon',
    'apps.admin_app',
    'apps.moments_app',
]

# REST Framework 配置
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'OPTIONS': {
            # 优化SQLite性能，减少IO操作
            'timeout': 20,  # 数据库锁超时时间（秒）
        },
    }
}

# SQLite性能优化配置
# 在应用启动时设置SQLite的WAL模式（Write-Ahead Logging），提高并发性能
import sqlite3
from django.db.backends.signals import connection_created

def activate_sqlite_wal(sender, connection, **kwargs):
    """激活SQLite的WAL模式，提高并发性能，减少IO竞争"""
    if connection.vendor == 'sqlite':
        with connection.cursor() as cursor:
            cursor.execute('PRAGMA journal_mode=WAL;')  # 启用WAL模式
            cursor.execute('PRAGMA synchronous=NORMAL;')  # 平衡性能和安全性
            cursor.execute('PRAGMA cache_size=-64000;')  # 设置64MB缓存
            cursor.execute('PRAGMA temp_store=MEMORY;')  # 临时表存储在内存中

connection_created.connect(activate_sqlite_wal)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'apps' / 'marathon' / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS配置
CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',  # React默认开发端口
    'http://127.0.0.1:3000',  # 本地IP（Edge浏览器可能使用）
    'http://172.31.180.1:3000',  # 云服务器内网前端端口
    'http://8.153.95.63:3000',  # 云服务器公网前端端口
]
CORS_ALLOW_CREDENTIALS = True  # 允许携带cookies
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]  # 允许的请求头

# Session配置
SESSION_COOKIE_HTTPONLY = False  # 允许JavaScript访问cookie（开发环境）
SESSION_COOKIE_SAMESITE = 'Lax'  # 允许跨站点cookie（Lax适用于同站请求，localhost和127.0.0.1视为同站）
SESSION_COOKIE_SECURE = False  # 开发环境不需要HTTPS（生产环境应设为True）
SESSION_COOKIE_DOMAIN = None  # 不限制域名，允许localhost和127.0.0.1
# 优化：使用缓存存储session，减少数据库IO操作
# 如果缓存不可用，会自动回退到数据库存储
SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'  # 使用缓存+数据库存储session（减少IO）
SESSION_CACHE_ALIAS = 'default'  # 使用默认缓存

# 媒体文件配置
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# 缓存配置
# 使用内存缓存（适合个人网站，部署简单，性能优秀）
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'OPTIONS': {
            'MAX_ENTRIES': 1000,  # 最大缓存条目数
        }
    }
}

# 缓存超时设置（秒）
CACHE_TIMEOUT = {
    'SHORT': 60 * 5,      # 5分钟 - 适用于频繁变化的数据
    'MEDIUM': 60 * 30,    # 30分钟 - 适用于中等频率变化的数据
    'LONG': 60 * 60 * 2,  # 2小时 - 适用于静态数据
}
