# Generated by Django 5.2.3 on 2026-01-17 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminsetting",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="admin/avatar/",
                verbose_name="头像图片",
            ),
        ),
        migrations.AddField(
            model_name="adminsetting",
            name="carousel_images",
            field=models.JSONField(
                blank=True, default=list, verbose_name="轮播图图片列表"
            ),
        ),
        migrations.AddField(
            model_name="adminsetting",
            name="decorative_icons",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="装饰图标配置"
            ),
        ),
    ]
