# Generated by Django 4.2.27 on 2026-01-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marathon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100, verbose_name='赛事名称')),
                ('event_date', models.DateField(verbose_name='赛事日期')),
                ('location', models.CharField(max_length=100, verbose_name='赛事地点')),
                ('distance', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='距离(公里)')),
                ('finish_time', models.CharField(max_length=20, verbose_name='完赛时间')),
                ('pace', models.CharField(max_length=20, verbose_name='配速')),
                ('certificate', models.ImageField(blank=True, null=True, upload_to='marathon/certificates/', verbose_name='完赛证书')),
                ('description', models.TextField(blank=True, verbose_name='赛事描述')),
                ('event_log', models.TextField(blank=True, verbose_name='赛事日志(Markdown格式)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '马拉松赛事',
                'verbose_name_plural': '马拉松赛事',
                'ordering': ['-event_date'],
            },
        ),
    ]
