# Generated by Django 4.2.27 on 2026-01-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marathon',
            name='event_type',
            field=models.CharField(choices=[('full', '全程马拉松'), ('half', '半程马拉松'), ('other', '其他距离')], default='other', max_length=10, verbose_name='赛事类型'),
        ),
    ]
