# Generated by Django 5.2.3 on 2026-01-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0002_marathon_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='marathon',
            name='city',
            field=models.CharField(blank=True, max_length=50, verbose_name='城市'),
        ),
        migrations.AddField(
            model_name='marathon',
            name='district',
            field=models.CharField(blank=True, max_length=50, verbose_name='区/县'),
        ),
        migrations.AddField(
            model_name='marathon',
            name='province',
            field=models.CharField(blank=True, max_length=50, verbose_name='省份'),
        ),
    ]
