# Generated by Django 5.2.3 on 2026-01-06 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0003_marathon_city_marathon_district_marathon_province'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='城市名称')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='城市代码')),
            ],
            options={
                'verbose_name': '城市',
                'verbose_name_plural': '城市',
                'ordering': ['province', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='省份名称')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='省份代码')),
            ],
            options={
                'verbose_name': '省份',
                'verbose_name_plural': '省份',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='区/县名称')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='区/县代码')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='marathon.city', verbose_name='所属城市')),
            ],
            options={
                'verbose_name': '区/县',
                'verbose_name_plural': '区/县',
                'ordering': ['city', 'id'],
            },
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='marathon.province', verbose_name='所属省份'),
        ),
    ]
