# Generated by Django 5.2.3 on 2026-01-06 11:39

from django.db import migrations

def create_location_data(apps, schema_editor):
    """创建地区数据"""
    Province = apps.get_model('marathon', 'Province')
    City = apps.get_model('marathon', 'City')
    
    # 省份数据
    provinces_data = [
        ('110000', '北京市'),
        ('120000', '天津市'),
        ('130000', '河北省'),
        ('140000', '山西省'),
        ('150000', '内蒙古自治区'),
        ('210000', '辽宁省'),
        ('220000', '吉林省'),
        ('230000', '黑龙江省'),
        ('310000', '上海市'),
        ('320000', '江苏省'),
        ('330000', '浙江省'),
        ('340000', '安徽省'),
        ('350000', '福建省'),
        ('360000', '江西省'),
        ('370000', '山东省'),
        ('410000', '河南省'),
        ('420000', '湖北省'),
        ('430000', '湖南省'),
        ('440000', '广东省'),
        ('450000', '广西壮族自治区'),
        ('460000', '海南省'),
        ('500000', '重庆市'),
        ('510000', '四川省'),
        ('520000', '贵州省'),
        ('530000', '云南省'),
        ('540000', '西藏自治区'),
        ('610000', '陕西省'),
        ('620000', '甘肃省'),
        ('630000', '青海省'),
        ('640000', '宁夏回族自治区'),
        ('650000', '新疆维吾尔自治区'),
    ]
    
    # 城市数据（代码格式：省份代码+城市代码）
    cities_data = [
        # 北京市
        ('110100', '北京市', '110000'),
        # 天津市
        ('120100', '天津市', '120000'),
        # 上海市
        ('310100', '上海市', '310000'),
        # 重庆市
        ('500100', '重庆市', '500000'),
        # 广东省
        ('440100', '广州市', '440000'),
        ('440300', '深圳市', '440000'),
        ('440400', '珠海市', '440000'),
        ('440600', '佛山市', '440000'),
        # 江苏省
        ('320200', '无锡市', '320000'),
        ('320100', '南京市', '320000'),
        # 浙江省
        ('330100', '杭州市', '330000'),
        # 四川省
        ('510100', '成都市', '510000'),
        # 福建省
        ('350200', '厦门市', '350000'),
        ('350100', '福州市', '350000'),
    ]
    
    # 创建省份
    province_map = {}
    for code, name in provinces_data:
        province = Province.objects.create(code=code, name=name)
        province_map[code] = province
    
    # 创建城市
    for code, name, province_code in cities_data:
        province = province_map[province_code]
        City.objects.create(code=code, name=name, province=province)


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0004_city_province_district_city_province'),
    ]

    operations = [
        migrations.RunPython(create_location_data),
    ]
