# Generated by Django 5.2.3 on 2026-01-06 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0005_auto_20260106_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='marathon',
            name='city_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marathon_cities', to='marathon.city', verbose_name='城市'),
        ),
        migrations.AddField(
            model_name='marathon',
            name='district_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marathon_districts', to='marathon.district', verbose_name='区/县'),
        ),
        migrations.AddField(
            model_name='marathon',
            name='province_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marathon_provinces', to='marathon.province', verbose_name='省份'),
        ),
    ]
