# Generated by Django 5.2.3 on 2026-01-07 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0006_marathon_city_obj_marathon_district_obj_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marathon',
            name='distance',
        ),
        migrations.AlterField(
            model_name='marathon',
            name='event_type',
            field=models.CharField(choices=[('5km', '5KM'), ('10km', '10KM'), ('15km', '15KM'), ('half', '半程马拉松'), ('full', '全程马拉松')], default='full', max_length=10, verbose_name='赛事类型'),
        ),
    ]
