# Generated by Django 5.2.3 on 2026-01-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0007_remove_marathon_distance_alter_marathon_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarathonRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100, verbose_name='赛事名称')),
                ('event_date', models.DateField(verbose_name='赛事日期')),
                ('location', models.CharField(max_length=100, verbose_name='赛事地点')),
                ('province', models.CharField(blank=True, max_length=50, verbose_name='省份')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='城市')),
                ('district', models.CharField(blank=True, max_length=50, verbose_name='区/县')),
                ('event_type', models.CharField(choices=[('5km', '5KM'), ('10km', '10KM'), ('15km', '15KM'), ('half', '半程马拉松'), ('full', '全程马拉松')], default='full', max_length=10, verbose_name='赛事类型')),
                ('registration_status', models.CharField(choices=[('preparing', '准备报名'), ('pending', '待抽签'), ('won', '已中签'), ('lost', '未中签'), ('abandoned', '已弃赛')], default='preparing', max_length=20, verbose_name='报名状态')),
                ('registration_date', models.DateField(blank=True, null=True, verbose_name='报名时间')),
                ('registration_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='报名费用')),
                ('draw_date', models.DateField(blank=True, null=True, verbose_name='出签时间')),
                ('transport', models.CharField(blank=True, choices=[('booked', '已预定'), ('not_booked', '未预定'), ('local', '本地不需要')], max_length=20, null=True, verbose_name='交通信息')),
                ('accommodation', models.CharField(blank=True, choices=[('booked', '已预定'), ('not_booked', '未预定'), ('local', '本地不需要')], max_length=20, null=True, verbose_name='住宿信息')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '报名赛事',
                'verbose_name_plural': '报名赛事',
                'ordering': ['event_date'],
            },
        ),
    ]
