# Generated by Django 5.2.3 on 2026-01-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0008_marathonregistration'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='marathon',
            index=models.Index(fields=['event_date'], name='marathon_ma_event_d_87305a_idx'),
        ),
        migrations.AddIndex(
            model_name='marathon',
            index=models.Index(fields=['event_type'], name='marathon_ma_event_t_ebdaeb_idx'),
        ),
        migrations.AddIndex(
            model_name='marathon',
            index=models.Index(fields=['province_obj'], name='marathon_ma_provinc_66bb10_idx'),
        ),
        migrations.AddIndex(
            model_name='marathon',
            index=models.Index(fields=['city_obj'], name='marathon_ma_city_ob_94f4aa_idx'),
        ),
        migrations.AddIndex(
            model_name='marathon',
            index=models.Index(fields=['district_obj'], name='marathon_ma_distric_fe1d10_idx'),
        ),
        migrations.AddIndex(
            model_name='marathon',
            index=models.Index(fields=['event_date', 'event_type'], name='marathon_ma_event_d_70c900_idx'),
        ),
        migrations.AddIndex(
            model_name='marathonregistration',
            index=models.Index(fields=['event_date'], name='marathon_ma_event_d_f879bf_idx'),
        ),
        migrations.AddIndex(
            model_name='marathonregistration',
            index=models.Index(fields=['event_type'], name='marathon_ma_event_t_889990_idx'),
        ),
        migrations.AddIndex(
            model_name='marathonregistration',
            index=models.Index(fields=['registration_status'], name='marathon_ma_registr_283dd2_idx'),
        ),
        migrations.AddIndex(
            model_name='marathonregistration',
            index=models.Index(fields=['event_date', 'registration_status'], name='marathon_ma_event_d_1a47ff_idx'),
        ),
    ]
