# Generated by Django 5.2.3 on 2026-01-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0009_marathon_marathon_ma_event_d_87305a_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marathonregistration',
            name='registration_status',
            field=models.CharField(choices=[('preparing', '准备报名'), ('pending', '待抽签'), ('won', '已中签'), ('lost', '未中签'), ('abandoned', '已弃赛'), ('waitlist', '候补中')], default='preparing', max_length=20, verbose_name='报名状态'),
        ),
    ]
