# Generated by Django 5.2.3 on 2026-01-10 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0010_alter_marathonregistration_registration_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='marathonregistration',
            name='city_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_cities', to='marathon.city', verbose_name='城市'),
        ),
        migrations.AddField(
            model_name='marathonregistration',
            name='district_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_districts', to='marathon.district', verbose_name='区/县'),
        ),
        migrations.AddField(
            model_name='marathonregistration',
            name='province_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_provinces', to='marathon.province', verbose_name='省份'),
        ),
    ]
