# Generated by Django 5.2.3 on 2026-01-07 09:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=200, verbose_name='文字内容')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='是否置顶')),
                ('tags', models.CharField(blank=True, max_length=200, verbose_name='标签')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '朋友圈',
                'verbose_name_plural': '朋友圈',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', '图片'), ('live', 'Live图'), ('video', '视频')], max_length=10, verbose_name='媒体类型')),
                ('file', models.FileField(upload_to='posts/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'mp4', 'mov', 'avi', 'webm'])], verbose_name='媒体文件')),
                ('order', models.IntegerField(default=0, verbose_name='排序顺序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='moments_app.post', verbose_name='朋友圈')),
            ],
            options={
                'verbose_name': '朋友圈媒体',
                'verbose_name_plural': '朋友圈媒体',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
