# Generated by Django 5.2.3 on 2026-01-11 00:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moments_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="postmedia",
            name="video_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="posts/%Y/%m/%d/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mov", "mp4"]
                    )
                ],
                verbose_name="Live Photo视频",
            ),
        ),
        migrations.AlterField(
            model_name="postmedia",
            name="file",
            field=models.FileField(
                upload_to="posts/%Y/%m/%d/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "jpg",
                            "jpeg",
                            "png",
                            "gif",
                            "mp4",
                            "mov",
                            "avi",
                            "webm",
                            "heic",
                            "heif",
                        ]
                    )
                ],
                verbose_name="媒体文件",
            ),
        ),
    ]
